.header on
.mode COLUMN

CREATE TABLE Protein (
    prot_ID integer,
    prot_seq integer,
    locus_NCBI_ID varchar not null,
    uniprot_ID varchar not null,
    structural_prot_type integer, -- to define if it is an hexamer, pentamer, pseudohexamer (trimer) or not structural,
    primary key(prot_ID)
);

CREATE TABLE Gene (
    gene_name integer,
    gene_ID integer,
    dna_seq integer,-- If I have the DNA seq here I am duplicating info
    primary key(gene_ID)
);

CREATE TABLE Protein_gene (
    prot_ID integer,
    gene_ID integer,
    name_rank integer,
    -- primary gene gets rank 1; other names get 2, 3, ... Changed from bolean to be able to use UNIQUE
    -- to make a protein:gene relationship primary (promote it), then:
    -- 1. move primary relationship to name_rank of current largest number + 1
    -- 2. mover promoted gene to have name_rank 1
    foreign key(prot_ID) references Protein(prot_ID),
    foreign key(gene_ID) references Gene(gene_ID),
    UNIQUE(prot_id, gene_ID, name_rank)
    -- to make sure no protein has more than one main name
);

CREATE TABLE Taxon (
    tax_ID integer,
    tax_ref varchar not null,
    -- ref number in remote db
    tax_db varchar not null,
    -- stores whether NCBI or GTDB
    specie integer,
    genus integer,
    family integer,
    order_tax integer,
    phylum integer,
    class integer,
    strain integer,
    primary key(tax_ID)
);

CREATE TABLE Protein_taxon (
    prot_ID integer,
    tax_ID integer,
    foreign key(prot_ID) references Protein(prot_ID),
    foreign key(tax_ID) references Taxon(tax_ID)
);

CREATE TABLE Pdb (
-- if empty alphafold or other software will be used to predict structure
    pdb_ID integer,
    pdb_rscb_acc_1 varchar,
    pdb_rscb_acc_2 varchar,
    -- primary_pdb boolean. It does not matter which one is primary. Not needed
    primary key(pdb_ID)
);

CREATE TABLE Protein_pdb (
    pdb_ID integer,
    prot_ID integer,
    foreign key(prot_ID) references Protein(prot_ID),
    foreign key(pdb_ID) references Pdb(pdb_ID)
);

CREATE TABLE Domain (
    domain_ID integer,
    dom_ref_fam varchar not null,
    -- domain accession in remote db
    dom_ext_source integer not null,
    -- domain database, such as pfam, CDD...
    primary key(domain_ID)
);

CREATE TABLE Protein_domain (
    domain_ID integer,
    prot_ID integer,
    foreign key(prot_ID) references Protein(prot_ID),
    foreign key(domain_ID) references Domain(domain_ID)
);

CREATE TABLE Isoforms (
    canonical_prot_ID integer,
    isoform_prot_ID integer,
    -- Isoform ID is related to those proteins that may have to RBD
    -- 2 proteins from he same DNA seq, such as pduB and pduB'
    foreign key(canonical_prot_ID) references Protein(prot_ID),
    foreign key(isoform_prot_ID) references Protein(prot_ID)
);

CREATE TABLE Function_GO (
    go_ID integer, -- added as there was no ID assigned
    go_ext_ID varchar,
    -- ref number in GO db
    go_type varchar,
    -- MF (molecular function), CC (cellular compartment), or BP (biological process)
    go_description varchar,
    -- text description of the function
    primary key(go_ID)
);

CREATE TABLE Protein_GO (
    go_ID integer,
    prot_ID integer,
    foreign key(go_ID) references Function_GO(go_ID),
    foreign key(prot_ID) references Protein(prot_ID)
);

CREATE TABLE Enzyme_path (
    path_ID integer,
    KO varchar,
    -- ref number from Kegg Ontology db
    primary key(path_ID)
);

CREATE TABLE Protein_path (
    path_ID integer,
    prot_ID integer,
    foreign key(path_ID) references Enzyme_path(path_ID),
    foreign key(prot_ID) references Protein(prot_ID)
);

CREATE TABLE Complex (
    complex_ID integer,
    -- can be the native complex, e.g.: pdu operon, or a synthetic one, e.g.: pduABJMNK
    complex_type integer,
    -- need to decide which classification to use. Axen paper?
    complex_activity integer,
    -- Active/inactice
    assembly_exp_tested integer,
    -- Is the assembly of this compartment experimentally tested (Y/N)?
    -- Consider whether if Y answer paper references should be added. How?
    complex_source integer,
    -- Native complex, experimental complex, theorical complex
    primary key(complex_ID)
);-- Should I add classification for native complext?

CREATE TABLE Protein_complex(
    complex_ID integer,
    -- Several proteins can belong to the same complex and one protein to several complexes
    prot_ID integer,
    prot_essential_assembly integer, -- is this protein essential for the assembly of the complex (Y/N)?
    prot_interact_ID integer, -- ask Leighton, is about direct interation not complex
    copy_number integer, -- protein copy number in complex (stecheometry)
     -- structural_prot_type integer, -- move to protein table to avoid redundances
    foreign key(complex_ID) references Complex(complex_ID),
    foreign key(prot_ID) references Protein(prot_ID),
    foreign key(prot_interact_ID) references Protein(prot_ID)
);

-- DATA INTRODUCTION:

-- Protein table:
INSERT INTO Protein(prot_ID, prot_seq, locus_NCBI_ID, uniprot_ID, structural_prot_type) VALUES (1,
"MHLARVTGVVVSTQKSPSLVGKKLLLVRRVSADGELPASPVSGDEVAVDSVGAGTGELVLLSSGSSARHVFSGPNEAIDLAIVGIVDTLSR",
"JMV71_RS09440",
"P0DUV6", "BMC-P"
);

INSERT INTO Protein(prot_ID, prot_seq, locus_NCBI_ID, uniprot_ID, structural_prot_type) VALUES (2,
"MADALGMIEVRGFVGMVEAADAMVKAAKVELIGYEKTGGGYVTAVVRGDVAAVKAATEAGQRAAERVGEVVAVHVIPRPHVNVDAALPLGRTPGMDKSA",
"HOCH_RS28905",
"D0LID5", "BMC-H"
);

INSERT INTO Protein(prot_ID, prot_seq, locus_NCBI_ID, uniprot_ID, structural_prot_type) VALUES (3,
"MNTSELETLIRNILSEQLAPAKAEVKGNGIFPSVSEAIDAAHQAFLRYQQCPLKTRSAIINALREELTPHLASLAAESAAETGMGNKEDKFLKNKAALDNTPGIEDLTTTALTGDGGMVLFEYSPFGVIGSVAPSTNPTETIINNSISMLAAGNSVYFSPHPGAKAVSLKLITMIEDIAFRCCGIRNLVVTVTEPTFEATQQMMAHPKIAVLAITGGPGIVAMGMKSGKKVIGAGAGNPPCIVDETADLVKAAEDIINGASFDFNLPCIAEKSLIVVDAVAERLVQQMQSFGAMRLNSEEIDKLRAVCLPEGIANKQLVGKSPATLLEAAGIPVPAKAPRLLIGIVKADDPWVTSEQLMPMLPIVTVSDFDSALTLALKVEEGLHHTAIMHSQNVSRLNLAARTLQTSIFVKNGPSYAGIGVGGEGFTTFTIATPTGEGTTSARTFARSRRCVLTNGFSIR",
"JMV71_RS09430",
"B1VB75", null
);

INSERT INTO Protein(prot_ID, prot_seq, locus_NCBI_ID, uniprot_ID, structural_prot_type) VALUES (4,
"MAHDEQLWLTPRLQKAAALCNQTPAASDTPLWLGVDLGTCDVVSMVVDGNAQPVAVCLDWADVVRDGIVWDFFGAVTLVRRHLDTLEQQLGCRFTHAATSFPPGTDPRISINVLESAGLEVSHVLDEPTAVADLLALDNAGVVDIGGGTTGIAIVKQGKVTYSADEATGGHHISLTLAGNRRIPLEEAEQYKRSNAQEIWPVVKPVYEKMAEIVARHIEGQGIADLWLAGGSCMQPGVEALFRQRFPELQVHLPQHSLFMTPLAIANSGRAKAEGLYAS",
"STM2462",
"P0A206", null
);

INSERT INTO Protein(prot_ID, prot_seq, locus_NCBI_ID, uniprot_ID, structural_prot_type) VALUES (5,
"MPALDLIRPSVTAMRVIASVNDGFARELKLPPHIRSLGLITADSDDVTYIAADEATKQAMVEVVYGRSLYAGAAHGPSPTAGEVLIMLGGPNPAEVRAGLDAMVASIENGAAFQWANDAENTAFLAHVVSRTGSYLSSTAGIALGDPMAYLVAPPLEATFGIDAAMKSADVQLVTYVPPPSETNYSAAFLTGSQAACKACNAFTDAVLDIARNPVQRA",
"STM2456",
"P0A1C9", "BMC-T"
);

INSERT INTO Protein(prot_ID, prot_seq, locus_NCBI_ID, uniprot_ID, structural_prot_type) VALUES (6,
"MQQEALGMVETKGLTAAIEAADAMVKSANVMLVGYEKIGSGLVTVIVRGDVGAVKAATDAGAAAARNVGEVKAVHVIPRPHTDVEKILPKGIS",
"QRZ63_RS08710",
"P0DUM6", "BMC-H"
);

INSERT INTO Protein(prot_ID, prot_seq, locus_NCBI_ID, uniprot_ID, structural_prot_type) VALUES (7,
"MSSNELVDQIMAQVIARVATPEQQAIPENNPPTRETAMAEKSCSLTEFVGTAIGDTVGLVIANVDSALLDAMKLEKRYRSIGILGARTGAGPHIMAADEAVKATNTEVVSIELPRDTKGGAGHGSLIILGGNDVSDVKRGIEVALKELDRTFGDVYANEAGHIEMQYTARASYALEKAFGAPIGRACGVIVGAPASVGVLMADTALKSANVEVVAYSSPAHGTSFSNEAILVISGDSGAVRQAVISAREIGKTVLGTLGSEPKNDRPSYI",
null,
"B1VB63",  "BMC-T"-- cannot find locus ID
);

INSERT INTO Protein(prot_ID, prot_seq, locus_NCBI_ID, uniprot_ID, structural_prot_type) VALUES (8,
"MAEKSCSLTEFVGTAIGDTVGLVIANVDSALLDAMKLEKRYRSIGILGARTGAGPHIMAADEAVKATNTEVVSIELPRDTKGGAGHGSLIILGGNDVSDVKRGIEVALKELDRTFGDVYANEAGHIEMQYTARASYALEKAFGAPIGRACGVIVGAPASVGVLMADTALKSANVEVVAYSSPAHGTSFSNEAILVISGDSGAVRQAVISAREIGKTVLGTLGSEPKNDRPSYI",
null,
"B1VB63-2", "BMC-T" -- cannot find locus ID
);

-- Gene Table:
INSERT INTO Gene(gene_name, gene_ID, dna_seq) VALUES (1,
"pduN",
"ATGCATCTGGCACGGGTTACAGGCGTTGTGGTTTCCACGCAAAAATCTCCATCACTGGTGGGGAAGAAACTGTTGCTGGTACGTCGGGTGAGTGCGGACGGAGAACTTCCCGCGTCCCCTGTGAGTGGAGATGAAGTCGCGGTTGATTCTGTCGGCGCTGGAACTGGAGAACTGGTATTACTCAGCAGTGGCTCCAGCGCCAGACACGTTTTTTCCGGCCCTAATGAGGCCATCGATCTGGCTATCGTCGGCATTGTCGACACGCTTTCTCGTTAG"
);

INSERT INTO Gene(gene_name, gene_ID, dna_seq) VALUES (2,
"hoch_5815",
"ATGGCGGACGCACTGGGTATGATTGAAGTTCGTGGTTTTGTTGGTATGGTGGAAGCGGCGGATGCTATGGTGAAAGCGGCTAAAGTTGAACTGATTGGTTATGAAAAAACCGGCGGTGGCTACGTGACGGCAGTGGTTCGTGGTGATGTCGCAGCAGTTAAGGCAGCTACCGAAGCCGGTCAGCGTGCAGCAGAACGTGTTGGTGAAGTCGTGGCAGTTCATGTCATCCCGCGTCCGCACGTGAACGTTGATGCAGCTCTGCCGCTGGGTCGTACGCCGGGTATGGACAAAAGCGCGTAA"
);

INSERT INTO Gene(gene_name, gene_ID, dna_seq) VALUES (3,
"pduP",
"ATGAACACTTCAGAACTTGAAACCCTTATTCGTAACATTTTGAGTGAGCAACTTGCCCCGGCAAAAGCAGAAGTTAAGGGTAATGGAATTTTTCCGTCCGTTAGCGAAGCGATCGATGCCGCTCATCAGGCTTTTCTGCGTTATCAGCAATGTCCATTGAAAACCCGCAGCGCCATCATTAACGCCCTGCGAGAAGAGCTGACGCCTCACCTTGCTTCATTGGCTGCTGAAAGCGCTGCCGAAACGGGAATGGGCAACAAAGAGGATAAGTTCCTTAAAAATAAAGCTGCGTTGGACAATACCCCGGGCATCGAAGATCTCACCACCACGGCGCTTACTGGCGACGGCGGCATGGTGTTATTCGAGTATTCACCCTTTGGCGTGATTGGTTCCGTCGCCCCCAGTACCAACCCGACTGAAACCATTATTAACAACAGCATCAGTATGCTGGCTGCGGGAAATAGCGTTTATTTTAGCCCACATCCAGGTGCAAAAGCGGTCTCACTGAAGCTGATTACCATGATTGAAGATATTGCTTTTCGCTGCTGCGGGATTCGGAATCTTGTCGTCACGGTCACAGAACCCACTTTTGAGGCTACCCAGCAGATGATGGCGCACCCTAAAATCGCAGTTCTGGCGATTACCGGTGGTCCAGGCATTGTTGCTATGGGCATGAAAAGCGGGAAAAAAGTCATTGGCGCAGGCGCAGGTAATCCTCCCTGCATTGTTGATGAAACAGCCGACCTGGTTAAGGCGGCGGAAGATATCATCAATGGCGCATCCTTTGATTTCAACCTCCCCTGCATTGCTGAGAAGAGCCTGATTGTTGTTGATGCCGTTGCTGAACGACTGGTTCAACAAATGCAGTCTTTTGGCGCGATGCGACTCAATAGCGAAGAGATAGACAAACTGCGCGCAGTTTGTCTGCCAGAAGGAATAGCCAATAAACAACTGGTAGGGAAAAGCCCGGCAACCTTACTGGAAGCCGCGGGAATACCGGTTCCGGCAAAAGCACCTCGATTACTGATAGGTATCGTCAAGGCTGACGACCCATGGGTTACCAGCGAGCAACTGATGCCAATGCTCCCCATCGTAACGGTGAGCGATTTTGACAGCGCGTTAACGTTGGCCCTGAAGGTTGAAGAGGGATTGCATCACACCGCCATTATGCATTCGCAAAATGTGTCACGTCTGAACCTTGCCGCGCGCACGCTTCAGACCTCCATTTTTGTGAAAAATGGCCCCTCTTATGCTGGGATTGGCGTTGGTGGTGAAGGCTTTACCACCTTCACCATTGCAACGCCGACCGGCGAAGGAACGACATCTGCGCGCACTTTCGCACGCTCTCGTCGTTGCGTGCTGACAAACGGTTTTTCTATTCGCTAA"
);

INSERT INTO Gene(gene_name, gene_ID, dna_seq) VALUES (4,
"eutJ",
"TCAGCTTGCATAGAGTCCCTCCGCTTTCGCTCTCCCGCTGTTGGCTATCGCCAGCGGGGTCATAAACAGGCTGTGCTGCGGCAAATGCACCTGTAACTCCGGGAAACGCTGGCGAAATAACGCCTCCACGCCCGGCTGCATACAGGAGCCGCCCGCCAGCCATAAATCAGCAATTCCTTGCCCTTCAATGTGGCGAGCAACGATTTCCGCCATCTTTTCGTACACCGGCTTCACTACCGGCCAAATCTCCTGCGCATTGCTGCGCTTGTACTGTTCCGCCTCTTCCAGGGGAATACGGCGGTTGCCCGCCAGCGTCAGGGAGATATGGTGCCCGCCAGTGGCTTCATCGGCGGAGTAAGTCACCTTGCCCTGTTTGACGATGGCAATGCCGGTAGTGCCGCCGCCAATATCCACCACGCCTGCATTATCAAGCGCCAGCAGATCCGCTACCGCCGTCGGTTCATCCAGTACATGGCTGACTTCTAACCCGGCAGACTCCAGCACGTTGATCGAAATACGCGGGTCGGTGCCTGGCGGAAACGAGGTCGCCGCGTGGGTAAAGCGGCAGCCGAGCTGCTGTTCAAGGGTGTCGAGATGGCGGCGCACGAGGGTGACGGCGCCGAAGAAATCCCAGACGATGCCGTCACGCACAACGTCGGCCCAGTCAAGGCATACCGCCACCGGCTGGGCGTTGCCGTCGACCACCATCGACACCACGTCGCAGGTGCCCAAATCGACGCCCAGCCACAGCGGTGTATCGCTGGCGGCGGGCGTCTGGTTACACAGGGCCGCCGCTTTTTGCAGTCTTGGGGTGAGCCAGAGTTGTTCGTCGTGCGCCAT"
);

INSERT INTO Gene(gene_name, gene_ID, dna_seq) VALUES (5,
"eutL",
"ATGCCTGCATTAGATTTAATTCGACCTTCCGTGACTGCCATGCGCGTGATTGCCTCCGTGAATGACGGCTTTGCGCGGGAACTTAAATTACCGCCACATATACGTAGTCTCGGACTCATCACGGCAGATTCTGATGATGTGACCTATATTGCCGCTGACGAAGCGACAAAACAGGCGATGGTGGAAGTGGTCTATGGCCGCTCCCTCTATGCCGGGGCGGCTCACGGGCCGTCGCCTACCGCTGGTGAGGTGTTGATTATGCTGGGCGGACCGAACCCGGCGGAAGTGCGCGCCGGTCTGGATGCAATGGTCGCCAGCATTGAAAACGGCGCGGCGTTCCAGTGGGCGAACGATGCGGAAAATACCGCATTCCTGGCGCATGTGGTTTCGCGTACCGGCTCGTACCTCTCGTCTACCGCAGGTATCGCGCTGGGCGATCCAATGGCCTACCTGGTGGCGCCGCCGCTGGAAGCGACATTCGGCATTGACGCGGCGATGAAATCCGCTGACGTTCAGCTGGTGACTTACGTGCCGCCGCCGTCGGAAACCAACTATTCGGCCGCGTTCTTAACCGGAAGCCAGGCCGCGTGTAAAGCCGCCTGCAACGCCTTTACCGACGCCGTGCTGGATATCGCCCGTAACCCTGTCCAGCGTGCGTAA"
);

INSERT INTO Gene(gene_name, gene_ID, dna_seq) VALUES (6,
"pduA",
"ATGCAACAAGAAGCGTTAGGAATGGTAGAAACCAAAGGCTTAACTGCAGCCATAGAGGCCGCAGATGCAATGGTGAAGTCAGCCAATGTAATGCTGGTCGGCTACGAAAAAATTGGTTCGGGGCTGGTAACAGTTATTGTCCGCGGCGATGTCGGCGCAGTCAAAGCAGCAACAGATGCCGGTGCCGCCGCAGCCCGTAATGTGGGAGAAGTGAAAGCCGTACACGTTATCCCACGCCCGCATACCGATGTAGAAAAAATCTTACCGAAGGGAATTAGCTAA"
);

INSERT INTO Gene(gene_name, gene_ID, dna_seq) VALUES (7,
"pduB",
"ATGAGCAGCAATGAGCTGGTTGATCAGATCATGGCGCAGGTGATTGCTCGCGTGGCAACGCCGGAACAGCAGGCTATCCCTGAAAATAATCCTCCAACACGAGAAACGGCTATGGCAGAGAAAAGCTGCAGTTTAACGGAGTTTGTCGGTACTGCGATTGGCGACACCGTCGGTCTGGTAATCGCCAACGTGGACAGCGCCCTACTGGACGCAATGAAACTTGAAAAACGGTATCGCTCCATTGGCATCCTTGGCGCGCGTACTGGTGCAGGCCCGCACATCATGGCCGCAGATGAAGCGGTAAAAGCCACCAATACTGAAGTCGTCAGTATTGAGTTGCCACGTGATACCAAAGGCGGCGCGGGTCACGGTTCGCTGATTATTCTCGGCGGCAACGATGTTTCCGACGTGAAACGCGGAATTGAGGTTGCGCTGAAAGAACTGGATCGCACCTTTGGCGATGTGTATGCCAACGAAGCCGGTCACATCGAGATGCAATACACCGCACGCGCCAGCTACGCGCTGGAAAAAGCCTTTGGTGCACCGATTGGCCGTGCCTGTGGCGTGATCGTCGGCGCGCCGGCATCCGTTGGTGTCCTGATGGCTGATACTGCGCTGAAATCCGCCAACGTGGAAGTTGTGGCCTACAGCTCCCCTGCCCATGGCACCAGCTTCAGTAACGAAGCCATTCTGGTCATTTCAGGCGATTCCGGCGCTGTGCGTCAGGCCGTTATCTCCGCCCGCGAAATCGGTAAAACCGTACTCGGGACCCTCGGCTCAGAACCGAAAAACGATCGTCCGTCCTACATCTGA"
);

INSERT INTO Gene(gene_name, gene_ID, dna_seq) VALUES (8,
"pduB'",
"ATGAGCAGCAATGAGCTGGTTGATCAGATCATGGCGCAGGTGATTGCTCGCGTGGCAACGCCGGAACAGCAGGCTATCCCTGAAAATAATCCTCCAACACGAGAAACGGCTATGGCAGAGAAAAGCTGCAGTTTAACGGAGTTTGTCGGTACTGCGATTGGCGACACCGTCGGTCTGGTAATCGCCAACGTGGACAGCGCCCTACTGGACGCAATGAAACTTGAAAAACGGTATCGCTCCATTGGCATCCTTGGCGCGCGTACTGGTGCAGGCCCGCACATCATGGCCGCAGATGAAGCGGTAAAAGCCACCAATACTGAAGTCGTCAGTATTGAGTTGCCACGTGATACCAAAGGCGGCGCGGGTCACGGTTCGCTGATTATTCTCGGCGGCAACGATGTTTCCGACGTGAAACGCGGAATTGAGGTTGCGCTGAAAGAACTGGATCGCACCTTTGGCGATGTGTATGCCAACGAAGCCGGTCACATCGAGATGCAATACACCGCACGCGCCAGCTACGCGCTGGAAAAAGCCTTTGGTGCACCGATTGGCCGTGCCTGTGGCGTGATCGTCGGCGCGCCGGCATCCGTTGGTGTCCTGATGGCTGATACTGCGCTGAAATCCGCCAACGTGGAAGTTGTGGCCTACAGCTCCCCTGCCCATGGCACCAGCTTCAGTAACGAAGCCATTCTGGTCATTTCAGGCGATTCCGGCGCTGTGCGTCAGGCCGTTATCTCCGCCCGCGAAATCGGTAAAACCGTACTCGGGACCCTCGGCTCAGAACCGAAAAACGATCGTCCGTCCTACATCTGA"
);

-- Gene table. Alternative names:
INSERT INTO Gene(gene_name, gene_ID, dna_seq) VALUES (9,
"Bacterial microcompartment shell vertex protein PduN",
"ATGCATCTGGCACGGGTTACAGGCGTTGTGGTTTCCACGCAAAAATCTCCATCACTGGTGGGGAAGAAACTGTTGCTGGTACGTCGGGTGAGTGCGGACGGAGAACTTCCCGCGTCCCCTGTGAGTGGAGATGAAGTCGCGGTTGATTCTGTCGGCGCTGGAACTGGAGAACTGGTATTACTCAGCAGTGGCTCCAGCGCCAGACACGTTTTTTCCGGCCCTAATGAGGCCATCGATCTGGCTATCGTCGGCATTGTCGACACGCTTTCTCGTTAG"
);

INSERT INTO Gene(gene_name, gene_ID, dna_seq) VALUES (10,
"Propanediol utilization protein PduN",
"ATGCATCTGGCACGGGTTACAGGCGTTGTGGTTTCCACGCAAAAATCTCCATCACTGGTGGGGAAGAAACTGTTGCTGGTACGTCGGGTGAGTGCGGACGGAGAACTTCCCGCGTCCCCTGTGAGTGGAGATGAAGTCGCGGTTGATTCTGTCGGCGCTGGAACTGGAGAACTGGTATTACTCAGCAGTGGCTCCAGCGCCAGACACGTTTTTTCCGGCCCTAATGAGGCCATCGATCTGGCTATCGTCGGCATTGTCGACACGCTTTCTCGTTAG"
);

INSERT INTO Gene(gene_name, gene_ID, dna_seq) VALUES (11,
"Propanal dehydrogenase",
"ATGAACACTTCAGAACTTGAAACCCTTATTCGTAACATTTTGAGTGAGCAACTTGCCCCGGCAAAAGCAGAAGTTAAGGGTAATGGAATTTTTCCGTCCGTTAGCGAAGCGATCGATGCCGCTCATCAGGCTTTTCTGCGTTATCAGCAATGTCCATTGAAAACCCGCAGCGCCATCATTAACGCCCTGCGAGAAGAGCTGACGCCTCACCTTGCTTCATTGGCTGCTGAAAGCGCTGCCGAAACGGGAATGGGCAACAAAGAGGATAAGTTCCTTAAAAATAAAGCTGCGTTGGACAATACCCCGGGCATCGAAGATCTCACCACCACGGCGCTTACTGGCGACGGCGGCATGGTGTTATTCGAGTATTCACCCTTTGGCGTGATTGGTTCCGTCGCCCCCAGTACCAACCCGACTGAAACCATTATTAACAACAGCATCAGTATGCTGGCTGCGGGAAATAGCGTTTATTTTAGCCCACATCCAGGTGCAAAAGCGGTCTCACTGAAGCTGATTACCATGATTGAAGATATTGCTTTTCGCTGCTGCGGGATTCGGAATCTTGTCGTCACGGTCACAGAACCCACTTTTGAGGCTACCCAGCAGATGATGGCGCACCCTAAAATCGCAGTTCTGGCGATTACCGGTGGTCCAGGCATTGTTGCTATGGGCATGAAAAGCGGGAAAAAAGTCATTGGCGCAGGCGCAGGTAATCCTCCCTGCATTGTTGATGAAACAGCCGACCTGGTTAAGGCGGCGGAAGATATCATCAATGGCGCATCCTTTGATTTCAACCTCCCCTGCATTGCTGAGAAGAGCCTGATTGTTGTTGATGCCGTTGCTGAACGACTGGTTCAACAAATGCAGTCTTTTGGCGCGATGCGACTCAATAGCGAAGAGATAGACAAACTGCGCGCAGTTTGTCTGCCAGAAGGAATAGCCAATAAACAACTGGTAGGGAAAAGCCCGGCAACCTTACTGGAAGCCGCGGGAATACCGGTTCCGGCAAAAGCACCTCGATTACTGATAGGTATCGTCAAGGCTGACGACCCATGGGTTACCAGCGAGCAACTGATGCCAATGCTCCCCATCGTAACGGTGAGCGATTTTGACAGCGCGTTAACGTTGGCCCTGAAGGTTGAAGAGGGATTGCATCACACCGCCATTATGCATTCGCAAAATGTGTCACGTCTGAACCTTGCCGCGCGCACGCTTCAGACCTCCATTTTTGTGAAAAATGGCCCCTCTTATGCTGGGATTGGCGTTGGTGGTGAAGGCTTTACCACCTTCACCATTGCAACGCCGACCGGCGAAGGAACGACATCTGCGCGCACTTTCGCACGCTCTCGTCGTTGCGTGCTGACAAACGGTTTTTCTATTCGCTAA"
);

INSERT INTO Gene(gene_name, gene_ID, dna_seq) VALUES (12,
"Coenzyme-A-acylating propionaldehyde dehydrogenase",
"ATGAACACTTCAGAACTTGAAACCCTTATTCGTAACATTTTGAGTGAGCAACTTGCCCCGGCAAAAGCAGAAGTTAAGGGTAATGGAATTTTTCCGTCCGTTAGCGAAGCGATCGATGCCGCTCATCAGGCTTTTCTGCGTTATCAGCAATGTCCATTGAAAACCCGCAGCGCCATCATTAACGCCCTGCGAGAAGAGCTGACGCCTCACCTTGCTTCATTGGCTGCTGAAAGCGCTGCCGAAACGGGAATGGGCAACAAAGAGGATAAGTTCCTTAAAAATAAAGCTGCGTTGGACAATACCCCGGGCATCGAAGATCTCACCACCACGGCGCTTACTGGCGACGGCGGCATGGTGTTATTCGAGTATTCACCCTTTGGCGTGATTGGTTCCGTCGCCCCCAGTACCAACCCGACTGAAACCATTATTAACAACAGCATCAGTATGCTGGCTGCGGGAAATAGCGTTTATTTTAGCCCACATCCAGGTGCAAAAGCGGTCTCACTGAAGCTGATTACCATGATTGAAGATATTGCTTTTCGCTGCTGCGGGATTCGGAATCTTGTCGTCACGGTCACAGAACCCACTTTTGAGGCTACCCAGCAGATGATGGCGCACCCTAAAATCGCAGTTCTGGCGATTACCGGTGGTCCAGGCATTGTTGCTATGGGCATGAAAAGCGGGAAAAAAGTCATTGGCGCAGGCGCAGGTAATCCTCCCTGCATTGTTGATGAAACAGCCGACCTGGTTAAGGCGGCGGAAGATATCATCAATGGCGCATCCTTTGATTTCAACCTCCCCTGCATTGCTGAGAAGAGCCTGATTGTTGTTGATGCCGTTGCTGAACGACTGGTTCAACAAATGCAGTCTTTTGGCGCGATGCGACTCAATAGCGAAGAGATAGACAAACTGCGCGCAGTTTGTCTGCCAGAAGGAATAGCCAATAAACAACTGGTAGGGAAAAGCCCGGCAACCTTACTGGAAGCCGCGGGAATACCGGTTCCGGCAAAAGCACCTCGATTACTGATAGGTATCGTCAAGGCTGACGACCCATGGGTTACCAGCGAGCAACTGATGCCAATGCTCCCCATCGTAACGGTGAGCGATTTTGACAGCGCGTTAACGTTGGCCCTGAAGGTTGAAGAGGGATTGCATCACACCGCCATTATGCATTCGCAAAATGTGTCACGTCTGAACCTTGCCGCGCGCACGCTTCAGACCTCCATTTTTGTGAAAAATGGCCCCTCTTATGCTGGGATTGGCGTTGGTGGTGAAGGCTTTACCACCTTCACCATTGCAACGCCGACCGGCGAAGGAACGACATCTGCGCGCACTTTCGCACGCTCTCGTCGTTGCGTGCTGACAAACGGTTTTTCTATTCGCTAA"
);

INSERT INTO Gene(gene_name, gene_ID, dna_seq) VALUES (13,
"Propanediol utilization protein PduP",
"ATGAACACTTCAGAACTTGAAACCCTTATTCGTAACATTTTGAGTGAGCAACTTGCCCCGGCAAAAGCAGAAGTTAAGGGTAATGGAATTTTTCCGTCCGTTAGCGAAGCGATCGATGCCGCTCATCAGGCTTTTCTGCGTTATCAGCAATGTCCATTGAAAACCCGCAGCGCCATCATTAACGCCCTGCGAGAAGAGCTGACGCCTCACCTTGCTTCATTGGCTGCTGAAAGCGCTGCCGAAACGGGAATGGGCAACAAAGAGGATAAGTTCCTTAAAAATAAAGCTGCGTTGGACAATACCCCGGGCATCGAAGATCTCACCACCACGGCGCTTACTGGCGACGGCGGCATGGTGTTATTCGAGTATTCACCCTTTGGCGTGATTGGTTCCGTCGCCCCCAGTACCAACCCGACTGAAACCATTATTAACAACAGCATCAGTATGCTGGCTGCGGGAAATAGCGTTTATTTTAGCCCACATCCAGGTGCAAAAGCGGTCTCACTGAAGCTGATTACCATGATTGAAGATATTGCTTTTCGCTGCTGCGGGATTCGGAATCTTGTCGTCACGGTCACAGAACCCACTTTTGAGGCTACCCAGCAGATGATGGCGCACCCTAAAATCGCAGTTCTGGCGATTACCGGTGGTCCAGGCATTGTTGCTATGGGCATGAAAAGCGGGAAAAAAGTCATTGGCGCAGGCGCAGGTAATCCTCCCTGCATTGTTGATGAAACAGCCGACCTGGTTAAGGCGGCGGAAGATATCATCAATGGCGCATCCTTTGATTTCAACCTCCCCTGCATTGCTGAGAAGAGCCTGATTGTTGTTGATGCCGTTGCTGAACGACTGGTTCAACAAATGCAGTCTTTTGGCGCGATGCGACTCAATAGCGAAGAGATAGACAAACTGCGCGCAGTTTGTCTGCCAGAAGGAATAGCCAATAAACAACTGGTAGGGAAAAGCCCGGCAACCTTACTGGAAGCCGCGGGAATACCGGTTCCGGCAAAAGCACCTCGATTACTGATAGGTATCGTCAAGGCTGACGACCCATGGGTTACCAGCGAGCAACTGATGCCAATGCTCCCCATCGTAACGGTGAGCGATTTTGACAGCGCGTTAACGTTGGCCCTGAAGGTTGAAGAGGGATTGCATCACACCGCCATTATGCATTCGCAAAATGTGTCACGTCTGAACCTTGCCGCGCGCACGCTTCAGACCTCCATTTTTGTGAAAAATGGCCCCTCTTATGCTGGGATTGGCGTTGGTGGTGAAGGCTTTACCACCTTCACCATTGCAACGCCGACCGGCGAAGGAACGACATCTGCGCGCACTTTCGCACGCTCTCGTCGTTGCGTGCTGACAAACGGTTTTTCTATTCGCTAA"
);

INSERT INTO Gene(gene_name, gene_ID, dna_seq) VALUES (14,
"Ethanolamine utilization protein EutJ",
"TCAGCTTGCATAGAGTCCCTCCGCTTTCGCTCTCCCGCTGTTGGCTATCGCCAGCGGGGTCATAAACAGGCTGTGCTGCGGCAAATGCACCTGTAACTCCGGGAAACGCTGGCGAAATAACGCCTCCACGCCCGGCTGCATACAGGAGCCGCCCGCCAGCCATAAATCAGCAATTCCTTGCCCTTCAATGTGGCGAGCAACGATTTCCGCCATCTTTTCGTACACCGGCTTCACTACCGGCCAAATCTCCTGCGCATTGCTGCGCTTGTACTGTTCCGCCTCTTCCAGGGGAATACGGCGGTTGCCCGCCAGCGTCAGGGAGATATGGTGCCCGCCAGTGGCTTCATCGGCGGAGTAAGTCACCTTGCCCTGTTTGACGATGGCAATGCCGGTAGTGCCGCCGCCAATATCCACCACGCCTGCATTATCAAGCGCCAGCAGATCCGCTACCGCCGTCGGTTCATCCAGTACATGGCTGACTTCTAACCCGGCAGACTCCAGCACGTTGATCGAAATACGCGGGTCGGTGCCTGGCGGAAACGAGGTCGCCGCGTGGGTAAAGCGGCAGCCGAGCTGCTGTTCAAGGGTGTCGAGATGGCGGCGCACGAGGGTGACGGCGCCGAAGAAATCCCAGACGATGCCGTCACGCACAACGTCGGCCCAGTCAAGGCATACCGCCACCGGCTGGGCGTTGCCGTCGACCACCATCGACACCACGTCGCAGGTGCCCAAATCGACGCCCAGCCACAGCGGTGTATCGCTGGCGGCGGGCGTCTGGTTACACAGGGCCGCCGCTTTTTGCAGTCTTGGGGTGAGCCAGAGTTGTTCGTCGTGCGCCAT"
);

INSERT INTO Gene(gene_name, gene_ID, dna_seq) VALUES (15,
"Bacterial microcompartment shell protein EutL",
"ATGCCTGCATTAGATTTAATTCGACCTTCCGTGACTGCCATGCGCGTGATTGCCTCCGTGAATGACGGCTTTGCGCGGGAACTTAAATTACCGCCACATATACGTAGTCTCGGACTCATCACGGCAGATTCTGATGATGTGACCTATATTGCCGCTGACGAAGCGACAAAACAGGCGATGGTGGAAGTGGTCTATGGCCGCTCCCTCTATGCCGGGGCGGCTCACGGGCCGTCGCCTACCGCTGGTGAGGTGTTGATTATGCTGGGCGGACCGAACCCGGCGGAAGTGCGCGCCGGTCTGGATGCAATGGTCGCCAGCATTGAAAACGGCGCGGCGTTCCAGTGGGCGAACGATGCGGAAAATACCGCATTCCTGGCGCATGTGGTTTCGCGTACCGGCTCGTACCTCTCGTCTACCGCAGGTATCGCGCTGGGCGATCCAATGGCCTACCTGGTGGCGCCGCCGCTGGAAGCGACATTCGGCATTGACGCGGCGATGAAATCCGCTGACGTTCAGCTGGTGACTTACGTGCCGCCGCCGTCGGAAACCAACTATTCGGCCGCGTTCTTAACCGGAAGCCAGGCCGCGTGTAAAGCCGCCTGCAACGCCTTTACCGACGCCGTGCTGGATATCGCCCGTAACCCTGTCCAGCGTGCGTAA"
);

INSERT INTO Gene(gene_name, gene_ID, dna_seq) VALUES (16,
"Ethanolamine utilization protein EutL",
"ATGCCTGCATTAGATTTAATTCGACCTTCCGTGACTGCCATGCGCGTGATTGCCTCCGTGAATGACGGCTTTGCGCGGGAACTTAAATTACCGCCACATATACGTAGTCTCGGACTCATCACGGCAGATTCTGATGATGTGACCTATATTGCCGCTGACGAAGCGACAAAACAGGCGATGGTGGAAGTGGTCTATGGCCGCTCCCTCTATGCCGGGGCGGCTCACGGGCCGTCGCCTACCGCTGGTGAGGTGTTGATTATGCTGGGCGGACCGAACCCGGCGGAAGTGCGCGCCGGTCTGGATGCAATGGTCGCCAGCATTGAAAACGGCGCGGCGTTCCAGTGGGCGAACGATGCGGAAAATACCGCATTCCTGGCGCATGTGGTTTCGCGTACCGGCTCGTACCTCTCGTCTACCGCAGGTATCGCGCTGGGCGATCCAATGGCCTACCTGGTGGCGCCGCCGCTGGAAGCGACATTCGGCATTGACGCGGCGATGAAATCCGCTGACGTTCAGCTGGTGACTTACGTGCCGCCGCCGTCGGAAACCAACTATTCGGCCGCGTTCTTAACCGGAAGCCAGGCCGCGTGTAAAGCCGCCTGCAACGCCTTTACCGACGCCGTGCTGGATATCGCCCGTAACCCTGTCCAGCGTGCGTAA"
);

INSERT INTO Gene(gene_name, gene_ID, dna_seq) VALUES (17,
"Bacterial microcompartment protein homohexamer  pduA",
"ATGCAACAAGAAGCGTTAGGAATGGTAGAAACCAAAGGCTTAACTGCAGCCATAGAGGCCGCAGATGCAATGGTGAAGTCAGCCAATGTAATGCTGGTCGGCTACGAAAAAATTGGTTCGGGGCTGGTAACAGTTATTGTCCGCGGCGATGTCGGCGCAGTCAAAGCAGCAACAGATGCCGGTGCCGCCGCAGCCCGTAATGTGGGAGAAGTGAAAGCCGTACACGTTATCCCACGCCCGCATACCGATGTAGAAAAAATCTTACCGAAGGGAATTAGCTAA"
);

INSERT INTO Gene(gene_name, gene_ID, dna_seq) VALUES (18,
"Propanediol utilization protein PduA",
"ATGCAACAAGAAGCGTTAGGAATGGTAGAAACCAAAGGCTTAACTGCAGCCATAGAGGCCGCAGATGCAATGGTGAAGTCAGCCAATGTAATGCTGGTCGGCTACGAAAAAATTGGTTCGGGGCTGGTAACAGTTATTGTCCGCGGCGATGTCGGCGCAGTCAAAGCAGCAACAGATGCCGGTGCCGCCGCAGCCCGTAATGTGGGAGAAGTGAAAGCCGTACACGTTATCCCACGCCCGCATACCGATGTAGAAAAAATCTTACCGAAGGGAATTAGCTAA"
);

INSERT INTO Gene(gene_name, gene_ID, dna_seq) VALUES (19,
"Bacterial microcompartment shell protein PduA",
"ATGCAACAAGAAGCGTTAGGAATGGTAGAAACCAAAGGCTTAACTGCAGCCATAGAGGCCGCAGATGCAATGGTGAAGTCAGCCAATGTAATGCTGGTCGGCTACGAAAAAATTGGTTCGGGGCTGGTAACAGTTATTGTCCGCGGCGATGTCGGCGCAGTCAAAGCAGCAACAGATGCCGGTGCCGCCGCAGCCCGTAATGTGGGAGAAGTGAAAGCCGTACACGTTATCCCACGCCCGCATACCGATGTAGAAAAAATCTTACCGAAGGGAATTAGCTAA"
);

INSERT INTO Gene(gene_name, gene_ID, dna_seq) VALUES (20,
"Bacterial microcompartment shell protein PduB",
"ATGAGCAGCAATGAGCTGGTTGATCAGATCATGGCGCAGGTGATTGCTCGCGTGGCAACGCCGGAACAGCAGGCTATCCCTGAAAATAATCCTCCAACACGAGAAACGGCTATGGCAGAGAAAAGCTGCAGTTTAACGGAGTTTGTCGGTACTGCGATTGGCGACACCGTCGGTCTGGTAATCGCCAACGTGGACAGCGCCCTACTGGACGCAATGAAACTTGAAAAACGGTATCGCTCCATTGGCATCCTTGGCGCGCGTACTGGTGCAGGCCCGCACATCATGGCCGCAGATGAAGCGGTAAAAGCCACCAATACTGAAGTCGTCAGTATTGAGTTGCCACGTGATACCAAAGGCGGCGCGGGTCACGGTTCGCTGATTATTCTCGGCGGCAACGATGTTTCCGACGTGAAACGCGGAATTGAGGTTGCGCTGAAAGAACTGGATCGCACCTTTGGCGATGTGTATGCCAACGAAGCCGGTCACATCGAGATGCAATACACCGCACGCGCCAGCTACGCGCTGGAAAAAGCCTTTGGTGCACCGATTGGCCGTGCCTGTGGCGTGATCGTCGGCGCGCCGGCATCCGTTGGTGTCCTGATGGCTGATACTGCGCTGAAATCCGCCAACGTGGAAGTTGTGGCCTACAGCTCCCCTGCCCATGGCACCAGCTTCAGTAACGAAGCCATTCTGGTCATTTCAGGCGATTCCGGCGCTGTGCGTCAGGCCGTTATCTCCGCCCGCGAAATCGGTAAAACCGTACTCGGGACCCTCGGCTCAGAACCGAAAAACGATCGTCCGTCCTACATCTGA"
);

INSERT INTO Gene(gene_name, gene_ID, dna_seq) VALUES (21,
"Propanediol utilization protein PduB",
"ATGAGCAGCAATGAGCTGGTTGATCAGATCATGGCGCAGGTGATTGCTCGCGTGGCAACGCCGGAACAGCAGGCTATCCCTGAAAATAATCCTCCAACACGAGAAACGGCTATGGCAGAGAAAAGCTGCAGTTTAACGGAGTTTGTCGGTACTGCGATTGGCGACACCGTCGGTCTGGTAATCGCCAACGTGGACAGCGCCCTACTGGACGCAATGAAACTTGAAAAACGGTATCGCTCCATTGGCATCCTTGGCGCGCGTACTGGTGCAGGCCCGCACATCATGGCCGCAGATGAAGCGGTAAAAGCCACCAATACTGAAGTCGTCAGTATTGAGTTGCCACGTGATACCAAAGGCGGCGCGGGTCACGGTTCGCTGATTATTCTCGGCGGCAACGATGTTTCCGACGTGAAACGCGGAATTGAGGTTGCGCTGAAAGAACTGGATCGCACCTTTGGCGATGTGTATGCCAACGAAGCCGGTCACATCGAGATGCAATACACCGCACGCGCCAGCTACGCGCTGGAAAAAGCCTTTGGTGCACCGATTGGCCGTGCCTGTGGCGTGATCGTCGGCGCGCCGGCATCCGTTGGTGTCCTGATGGCTGATACTGCGCTGAAATCCGCCAACGTGGAAGTTGTGGCCTACAGCTCCCCTGCCCATGGCACCAGCTTCAGTAACGAAGCCATTCTGGTCATTTCAGGCGATTCCGGCGCTGTGCGTCAGGCCGTTATCTCCGCCCGCGAAATCGGTAAAACCGTACTCGGGACCCTCGGCTCAGAACCGAAAAACGATCGTCCGTCCTACATCTGA"
);

INSERT INTO Gene(gene_name, gene_ID, dna_seq) VALUES (22,
"Bacterial microcompartment protein homotrimer PduB",
"ATGAGCAGCAATGAGCTGGTTGATCAGATCATGGCGCAGGTGATTGCTCGCGTGGCAACGCCGGAACAGCAGGCTATCCCTGAAAATAATCCTCCAACACGAGAAACGGCTATGGCAGAGAAAAGCTGCAGTTTAACGGAGTTTGTCGGTACTGCGATTGGCGACACCGTCGGTCTGGTAATCGCCAACGTGGACAGCGCCCTACTGGACGCAATGAAACTTGAAAAACGGTATCGCTCCATTGGCATCCTTGGCGCGCGTACTGGTGCAGGCCCGCACATCATGGCCGCAGATGAAGCGGTAAAAGCCACCAATACTGAAGTCGTCAGTATTGAGTTGCCACGTGATACCAAAGGCGGCGCGGGTCACGGTTCGCTGATTATTCTCGGCGGCAACGATGTTTCCGACGTGAAACGCGGAATTGAGGTTGCGCTGAAAGAACTGGATCGCACCTTTGGCGATGTGTATGCCAACGAAGCCGGTCACATCGAGATGCAATACACCGCACGCGCCAGCTACGCGCTGGAAAAAGCCTTTGGTGCACCGATTGGCCGTGCCTGTGGCGTGATCGTCGGCGCGCCGGCATCCGTTGGTGTCCTGATGGCTGATACTGCGCTGAAATCCGCCAACGTGGAAGTTGTGGCCTACAGCTCCCCTGCCCATGGCACCAGCTTCAGTAACGAAGCCATTCTGGTCATTTCAGGCGATTCCGGCGCTGTGCGTCAGGCCGTTATCTCCGCCCGCGAAATCGGTAAAACCGTACTCGGGACCCTCGGCTCAGAACCGAAAAACGATCGTCCGTCCTACATCTGA"
);

-- Protein_Gene Table:
INSERT INTO Protein_gene(prot_ID, gene_ID, name_rank) VALUES (1,1,1);
INSERT INTO Protein_gene(prot_ID, gene_ID, name_rank) VALUES (1,9,2);
INSERT INTO Protein_gene(prot_ID, gene_ID, name_rank) VALUES (1,10,3);
INSERT INTO Protein_gene(prot_ID, gene_ID, name_rank) VALUES (2,2,1);
INSERT INTO Protein_gene(prot_ID, gene_ID, name_rank) VALUES (3,11,2);
INSERT INTO Protein_gene(prot_ID, gene_ID, name_rank) VALUES (3,12,3);
INSERT INTO Protein_gene(prot_ID, gene_ID, name_rank) VALUES (3,13,4);
INSERT INTO Protein_gene(prot_ID, gene_ID, name_rank) VALUES (3,3,1);
INSERT INTO Protein_gene(prot_ID, gene_ID, name_rank) VALUES (4,14,2);
INSERT INTO Protein_gene(prot_ID, gene_ID, name_rank) VALUES (4,4,1);
INSERT INTO Protein_gene(prot_ID, gene_ID, name_rank) VALUES (5,15,2);
INSERT INTO Protein_gene(prot_ID, gene_ID, name_rank) VALUES (5,16,3);
INSERT INTO Protein_gene(prot_ID, gene_ID, name_rank) VALUES (5,5,1);
INSERT INTO Protein_gene(prot_ID, gene_ID, name_rank) VALUES (6,17,2);
INSERT INTO Protein_gene(prot_ID, gene_ID, name_rank) VALUES (6,18,3);
INSERT INTO Protein_gene(prot_ID, gene_ID, name_rank) VALUES (6,19,4);
INSERT INTO Protein_gene(prot_ID, gene_ID, name_rank) VALUES (6,6,1);
INSERT INTO Protein_gene(prot_ID, gene_ID, name_rank) VALUES (7,20,2);
INSERT INTO Protein_gene(prot_ID, gene_ID, name_rank) VALUES (7,21,3);
INSERT INTO Protein_gene(prot_ID, gene_ID, name_rank) VALUES (7,22,4);
INSERT INTO Protein_gene(prot_ID, gene_ID, name_rank) VALUES (7,7,1);
INSERT INTO Protein_gene(prot_ID, gene_ID, name_rank) VALUES (8,8,1);

-- Taxon table:
INSERT INTO Taxon(tax_ID,tax_ref,tax_db,specie, genus, family, order_tax, phylum, class, strain)
VALUES (1, "546", "NCBI", "Citrobacter Freundii", "Citrobacter",
"Enterobacteriaceae", "Enterobacterales","Pseudomonadota", "Gammaproteobacteria", null);
INSERT INTO Taxon(tax_ID,tax_ref,tax_db,specie, genus, family, order_tax, phylum, class, strain)
VALUES (2, "502025", "NCBI", "Haliangum ochraceum", "Haliangum","Kofleriaceae", "Haliangiales",
"Myxococcota","Mixococcia", "DSM 14365");
INSERT INTO Taxon(tax_ID,tax_ref,tax_db,specie, genus, family, order_tax, phylum, class, strain)
VALUES (3, "99287", "NCBI", "Salmonella typhimurium", "Salmonella","Enterobacteriaceae",
"Enterobacterales","Pseudomonadota", "Gammaproteobacteria", "LT2 / SGSC1412 / ATCC 700720");

-- Protein taxon table:
INSERT INTO Protein_taxon(prot_ID, tax_ID) VALUES (1,1);
INSERT INTO Protein_taxon(prot_ID, tax_ID) VALUES (2,2);
INSERT INTO Protein_taxon(prot_ID, tax_ID) VALUES (3,1);
INSERT INTO Protein_taxon(prot_ID, tax_ID) VALUES (4,3);
INSERT INTO Protein_taxon(prot_ID, tax_ID) VALUES (5,3);
INSERT INTO Protein_taxon(prot_ID, tax_ID) VALUES (6,1);
INSERT INTO Protein_taxon(prot_ID, tax_ID) VALUES (7,1);
INSERT INTO Protein_taxon(prot_ID, tax_ID) VALUES (8,1); -- Isoform has same functions so redundant. Think on how to link it

-- Pdb table:
INSERT INTO Pdb(pdb_ID,pdb_rscb_acc_1, pdb_rscb_acc_2) VALUES (1, "6NLU", "5DJB");
INSERT INTO Pdb(pdb_ID,pdb_rscb_acc_1, pdb_rscb_acc_2) VALUES (2, "4P7T", "4P7V");

-- Protein pdb table:
INSERT INTO Protein_pdb(pdb_ID, prot_ID) VALUES (2,1);
INSERT INTO Protein_pdb(pdb_ID, prot_ID) VALUES (6,2);

-- Domain database:
INSERT INTO Domain(domain_ID. dom_ref_fam, dom_ext_source) VALUES (1, "cd01614", "CDD");
INSERT INTO Domain(domain_ID. dom_ref_fam, dom_ext_source) VALUES (2, "PF03319", "Pfam");
INSERT INTO Domain(domain_ID. dom_ref_fam, dom_ext_source) VALUES (3, "cd07045", "CDD");
INSERT INTO Domain(domain_ID. dom_ref_fam, dom_ext_source) VALUES (4, "PF00936", "Pfam");
INSERT INTO Domain(domain_ID. dom_ref_fam, dom_ext_source) VALUES (5, "cd07121", "CDD");
INSERT INTO Domain(domain_ID. dom_ref_fam, dom_ext_source) VALUES (6, "PF00171", "Pfam");
INSERT INTO Domain(domain_ID. dom_ref_fam, dom_ext_source) VALUES (7, "cd00012", "CDD");
INSERT INTO Domain(domain_ID. dom_ref_fam, dom_ext_source) VALUES (8, "PF14450", "Pfam");
INSERT INTO Domain(domain_ID. dom_ref_fam, dom_ext_source) VALUES (9, "cd07050", "CDD");
INSERT INTO Domain(domain_ID. dom_ref_fam, dom_ext_source) VALUES (10, "PF00936", "Pfam");
INSERT INTO Domain(domain_ID. dom_ref_fam, dom_ext_source) VALUES (11, "cd07047", "CDD");
INSERT INTO Domain(domain_ID. dom_ref_fam, dom_ext_source) VALUES (12, "cd07048", "CDD");

-- Protein domain database:
INSERT INTO Protein_domain(domain_ID, prot_ID) VALUES (1,1);
INSERT INTO Protein_domain(domain_ID, prot_ID) VALUES (2,1);
INSERT INTO Protein_domain(domain_ID, prot_ID) VALUES (3,2);
INSERT INTO Protein_domain(domain_ID, prot_ID) VALUES (4,2);
INSERT INTO Protein_domain(domain_ID, prot_ID) VALUES (5,3);
INSERT INTO Protein_domain(domain_ID, prot_ID) VALUES (6,3);
INSERT INTO Protein_domain(domain_ID, prot_ID) VALUES (7,4);
INSERT INTO Protein_domain(domain_ID, prot_ID) VALUES (8,4);
INSERT INTO Protein_domain(domain_ID, prot_ID) VALUES (9,5);
INSERT INTO Protein_domain(domain_ID, prot_ID) VALUES (10,5);
INSERT INTO Protein_domain(domain_ID, prot_ID) VALUES (3,6);
INSERT INTO Protein_domain(domain_ID, prot_ID) VALUES (4,6);
INSERT INTO Protein_domain(domain_ID, prot_ID) VALUES (11,7);
INSERT INTO Protein_domain(domain_ID, prot_ID) VALUES (12,7);
INSERT INTO Protein_domain(domain_ID, prot_ID) VALUES (4,7);
INSERT INTO Protein_domain(domain_ID, prot_ID) VALUES (11,8); -- Isoform has same functions so redundant. Think on how to link it
INSERT INTO Protein_domain(domain_ID, prot_ID) VALUES (12,8); -- Isoform has same functions so redundant. Think on how to link it

-- Isoforms table:
INSERT INTO Isoforms(canonical_prot_ID,isoform_prot_ID) VALUES (7,8);

-- Function_GO table:
INSERT INTO Function_GO (go_ID, go_ext_ID,go_type,go_description) VALUES (1, "0051144", "BP", "propanediol catabolic process: 
The chemical reactions and pathways resulting in the breakdown of propanediol, a sweet, colorless, viscous, hygroscopic liquid with the formula CH3-CHOH-CH2OH.");
 --IN GO P instead of BP, C instead of CC, F instead of MF
INSERT INTO Function_GO (go_ID, go_ext_ID, go_type,go_description) VALUES (2, "0031469", "CC", "Bacterial microcompartment:
An organelle found in bacteria consisting of a proteinaceous coat containing metabolic enzymes whose purpose is the sequestration or concentration of 
metabolites and which has the appearance of a polygonal granule by electron microscopy.");
INSERT INTO Function_GO (go_ID, go_ext_ID, go_type,go_description) VALUES (3, "0016620", "MF", "oxidoreductase activity, acting on the aldehyde or oxo group of donors, NAD or NADP as acceptor:
Catalysis of an oxidation-reduction (redox) reaction in which an aldehyde or ketone (oxo) group acts as a hydrogen or electron donor and reduces NAD or NADP.");
INSERT INTO Function_GO (go_ID, go_ext_ID, go_type,go_description) VALUES (4, "0016491", "MF", "oxidoreductase activity: Catalysis of an oxidation-reduction (redox) reaction, 
a reversible chemical reaction in which the oxidation state of an atom or atoms within a molecule is altered. One substrate acts as a hydrogen or electron donor and 
becomes oxidized, while the other acts as hydrogen or electron acceptor and becomes reduced.");
INSERT INTO Function_GO (go_ID, go_ext_ID, go_type,go_description) VALUES (5, "0008774", "MF", "acetaldehyde dehydrogenase (acetylating) activity: Catalysis of the reaction: 
acetaldehyde + CoA + NAD+ = acetyl-CoA + NADH + H+.");
INSERT INTO Function_GO (go_ID, go_ext_ID, go_type,go_description) VALUES (6, "0046336", "BP", "ethanolamine catabolic process: The chemical reactions and pathways resulting in 
the breakdown of ethanolamine (2-aminoethanol), an important water-soluble base of phospholipid (phosphatidylethanolamine).");
INSERT INTO Function_GO (go_ID, go_ext_ID, go_type,go_description) VALUES (7, "0031471", "CC", "ethanolamine degradation polyhedral organelle: An organelle found in bacteria 
consisting of a proteinaceous coat containing enzymes for the degradation of ethanolamine whose purpose is the protection of the rest of the cell from the toxic 
acetaldehyde product of the enzyme ethanolamine ammonia lyase.");
INSERT INTO Function_GO (go_ID, go_ext_ID, go_type,go_description) VALUES (8, "0005198", "MF", "structural molecule activity: The action of a molecule that contributes to the 
structural integrity of a complex.");
INSERT INTO Function_GO (go_ID, go_ext_ID, go_type,go_description) VALUES (9, "0006091", "BP", "generation of precursor metabolites and energy: The chemical reactions and 
pathways resulting in the formation of precursor metabolites, substances from which energy is derived, and any process involved in the liberation of 
energy from these substances.");

-- Protein GO table:
INSERT INTO Protein_GO (go_ID, prot_ID) VALUES (1, 1);
INSERT INTO Protein_GO (go_ID, prot_ID) VALUES (2, 1);
INSERT INTO Protein_GO (go_ID, prot_ID) VALUES (2, 2);
INSERT INTO Protein_GO (go_ID, prot_ID) VALUES (1, 3);
INSERT INTO Protein_GO (go_ID, prot_ID) VALUES (2, 3);
INSERT INTO Protein_GO (go_ID, prot_ID) VALUES (3, 3);
INSERT INTO Protein_GO (go_ID, prot_ID) VALUES (4, 3);
INSERT INTO Protein_GO (go_ID, prot_ID) VALUES (5, 3);
INSERT INTO Protein_GO (go_ID, prot_ID) VALUES (6, 4);
INSERT INTO Protein_GO (go_ID, prot_ID) VALUES (6, 5);
INSERT INTO Protein_GO (go_ID, prot_ID) VALUES (2, 5);
INSERT INTO Protein_GO (go_ID, prot_ID) VALUES (7, 5);
INSERT INTO Protein_GO (go_ID, prot_ID) VALUES (8, 5);
INSERT INTO Protein_GO (go_ID, prot_ID) VALUES (9, 5);
INSERT INTO Protein_GO (go_ID, prot_ID) VALUES (1, 6);
INSERT INTO Protein_GO (go_ID, prot_ID) VALUES (2, 6);
INSERT INTO Protein_GO (go_ID, prot_ID) VALUES (1, 7);
INSERT INTO Protein_GO (go_ID, prot_ID) VALUES (2, 7);
INSERT INTO Protein_GO (go_ID, prot_ID) VALUES (8, 7);
INSERT INTO Protein_GO (go_ID, prot_ID) VALUES (1, 8); -- Isoform has same functions so redundant. Think on how to link it
INSERT INTO Protein_GO (go_ID, prot_ID) VALUES (2, 8); -- Isoform has same functions so redundant. Think on how to link it
INSERT INTO Protein_GO (go_ID, prot_ID) VALUES (8, 8); -- Isoform has same functions so redundant. Think on how to link it

-- Enzyme path table:
INSERT INTO Enzyme_path(path_ID, KO) VALUES (1, "K27269");
INSERT INTO Enzyme_path(path_ID, KO) VALUES (2, "K13922");
INSERT INTO Enzyme_path(path_ID, KO) VALUES (3, "K04024");
INSERT INTO Enzyme_path(path_ID, KO) VALUES (4, "K04026");
INSERT INTO Enzyme_path(path_ID, KO) VALUES (5, "K27260");
INSERT INTO Enzyme_path(path_ID, KO) VALUES (6, "K27263");

-- Protein path table:
INSERT INTO Protein_path(path_ID, prot_ID) VALUES (1,1);
INSERT INTO Protein_path(path_ID, prot_ID) VALUES (null, 2);
INSERT INTO Protein_path(path_ID, prot_ID) VALUES (2, 3);
INSERT INTO Protein_path(path_ID, prot_ID) VALUES (3, 4);
INSERT INTO Protein_path(path_ID, prot_ID) VALUES (4, 5);
INSERT INTO Protein_path(path_ID, prot_ID) VALUES (5, 6);
INSERT INTO Protein_path(path_ID, prot_ID) VALUES (6, 7);
INSERT INTO Protein_path(path_ID, prot_ID) VALUES (6, 8); -- Isoform has same functions so redundant. Think on how to link it

-- Complex database:
INSERT INTO Complex(complex_ID, complex_type, complex_activity, assembly_exp_tested, complex_source) VALUES (1, "Pdu1AB", "active", "Y", "native"); -- Classification by BMC caller. prot 6 classified as GRM4 (ignored)
INSERT INTO Complex(complex_ID, complex_type, complex_activity, assembly_exp_tested, complex_source) VALUES (2, "HO", "inactive", "Y", "experimental shell system");
INSERT INTO Complex(complex_ID, complex_type, complex_activity, assembly_exp_tested, complex_source) VALUES (3, "Eut1", "active", "Y", "native");
INSERT INTO Complex(complex_ID, complex_type, complex_activity, assembly_exp_tested, complex_source) VALUES (4, "Pdu1AB", "inactive", "Y", "experimental shell system"); -- complex without native enzymes pduABJKN
INSERT INTO Complex(complex_ID, complex_type, complex_activity, assembly_exp_tested, complex_source) VALUES (5, "Pdu1AB", "inactive", "Y", "experimental shell system"); -- complex without native enzymes pduABJKNUT
INSERT INTO Complex(complex_ID, complex_type, complex_activity, assembly_exp_tested, complex_source) VALUES (6, "Eut1", "inactive", "Y", "experimental shell system"); -- complex without native enzymes eutSMNLK
INSERT INTO Complex(complex_ID, complex_type, complex_activity, assembly_exp_tested, complex_source) VALUES (7, "HO", "active", "N", "native");

-- Protein complex table:
INSERT INTO Protein_complex(complex_ID, prot_ID, prot_essential_assembly, copy_number, prot_interact_ID) 
VALUES (1, 1, "Y", "Unknown", 6);
INSERT INTO Protein_complex(complex_ID, prot_ID, prot_essential_assembly, copy_number, prot_interact_ID) 
VALUES (4, 1, "Y", "Unknown", 6);
INSERT INTO Protein_complex(complex_ID, prot_ID, prot_essential_assembly, copy_number, prot_interact_ID) 
VALUES (5, 1, "Y", "Unknown", 6);
INSERT INTO Protein_complex(complex_ID, prot_ID, prot_essential_assembly, copy_number, prot_interact_ID) 
VALUES (1, 3, "N", "Unknown", 6); -- suspected interaction not confirmed. Add experimentally tested box here too?
INSERT INTO Protein_complex(complex_ID, prot_ID, prot_essential_assembly, copy_number, prot_interact_ID) 
VALUES (2, 2, "Y", "Unknown", "unknown");
INSERT INTO Protein_complex(complex_ID, prot_ID, prot_essential_assembly, copy_number, prot_interact_ID) 
VALUES (7, 2, "Unknown", "Unknown", "unknown");
INSERT INTO Protein_complex(complex_ID, prot_ID, prot_essential_assembly, copy_number, prot_interact_ID) 
VALUES (3, 4, "N", "Unknown", "Unknown");
INSERT INTO Protein_complex(complex_ID, prot_ID, prot_essential_assembly, copy_number, prot_interact_ID) 
VALUES (3, 5, "N", "Unknown", "Unknown");
INSERT INTO Protein_complex(complex_ID, prot_ID, prot_essential_assembly, copy_number, prot_interact_ID) 
VALUES (6, 5, "N", "Unknown", "Unknown");
INSERT INTO Protein_complex(complex_ID, prot_ID, prot_essential_assembly, copy_number, prot_interact_ID) 
VALUES (1, 6, "N", "Unknown", [7,8,1]); -- ask how to put several protein references
INSERT INTO Protein_complex(complex_ID, prot_ID, prot_essential_assembly, copy_number, prot_interact_ID) 
VALUES (4, 6, "N", "Unknown", [7,8,1]); -- ask how to put several protein references
INSERT INTO Protein_complex(complex_ID, prot_ID, prot_essential_assembly, copy_number, prot_interact_ID) 
VALUES (5, 6, "N", "Unknown", [7,8,1]); -- ask how to put several protein references
INSERT INTO Protein_complex(complex_ID, prot_ID, prot_essential_assembly, copy_number, prot_interact_ID) 
VALUES (1, 7, "Y", "Unknown", 6);
INSERT INTO Protein_complex(complex_ID, prot_ID, prot_essential_assembly, copy_number, prot_interact_ID) 
VALUES (4, 7, "Y", "Unknown", 6);
INSERT INTO Protein_complex(complex_ID, prot_ID, prot_essential_assembly, copy_number, prot_interact_ID) 
VALUES (5, 7, "Y", "Unknown", 6);
INSERT INTO Protein_complex(complex_ID, prot_ID, prot_essential_assembly, copy_number, prot_interact_ID) 
VALUES (1, 8, "Y", "Unknown", 6);
INSERT INTO Protein_complex(complex_ID, prot_ID, prot_essential_assembly, copy_number, prot_interact_ID) 
VALUES (4, 8, "Y", "Unknown", 6);
INSERT INTO Protein_complex(complex_ID, prot_ID, prot_essential_assembly, copy_number, prot_interact_ID) 
VALUES (5, 8, "Y", "Unknown", 6);